# Generated by Django 5.1.2 on 2024-11-08 19:37

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesite',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
